### ISSUE TITLE
Check for existence of PKG_PROG_PKG_CONFIG

### ISSUE THREAD

**Issue by rdiez** [AE1020/AE1020.github.io#1]
Many thanks for your article titled ["Why 'Possibly Undefined Macro' Means Install pkg-config"](https://ae1020.github.io/undefined-macro-pkg-config/).

I recently got hit by that same problem, and the information there helped me understand the underlying issue.

But there is one missing piece of advice for the Autoconf user:

```
# If macro PKG_PROG_PKG_CONFIG is not available, Autoconf generates a misleading error message,
# so check for existence first, and otherwise provide helpful advice.
m4_ifndef([PKG_PROG_PKG_CONFIG], [m4_fatal([Macro PKG_PROG_PKG_CONFIG is not available. It is usually defined in file pkg.m4 provided by package pkg-config.])])
```

**Comment by AE1020** [comment]
Glad you found it useful!  I wondered if anyone would ever actually read that.  :-)  If you read it and actually responded, that indicates maybe more than one people have.

But...that was actually written two years ago, which seems like lifetimes ago in terms of what I'm doing!  So much so that it's all back to voodoo again, and I am not 100% sure what your advice represents.

I'm thinking...you are suggesting a way to help the people writing configure.ac to be proactive, so that users will get a better message?

If I read that right...the article wasn't so much targeting the `configure.ac` author as the user.  And as far as making suggestions on improving it, I'd hope the improvement could be more generically applicable; when these little patches have to be thrown in everywhere it feels "dirtier" than it needs to be.

That said, it's good for articles that are already long and detailed and boring to cover all the bases.  So if I did read that right, I can throw in the point at the end.

**Comment by rdiez** [comment]
> I'm thinking...you are suggesting a way to help the people writing configure.ac
> to be proactive, so that users will get a better message?

Yes, that's right.

> And as far as making suggestions on improving it, I'd hope the
> improvement could be more generically applicable;

Yes, a generic solution would be better. But I don't think there is any other way with Autoconf and/or M4. It is probably a design decision that you cannot reverse now.

Besides, even if Autoconf could tell you exactly which macro is missing (PKG_PROG_PKG_CONFIG in this case), it wouldn't know what it is for, or what package or tool the user should install. It is hard to implement a generic but really helpful solution in this scenario.

That is why I always check upfront. I would rather bother myself once than bother every user every time. Here is an example of the way I code:

https://github.com/rdiez/Tools/blob/master/Background/background.sh

Look for `verify_tool_is_installed` in that script. Unlike Autoconf, Bash is perfectly able to tell you which command is missing, but my script still tells you where you could get it from. Even if the advice is not accurate, it gives you enough information to search on the Internet.

**Comment by AE1020** [comment]
> https://github.com/rdiez/Tools/blob/master/Background/background.sh

I like how much exposition you put in your code, it's very [Literate Programming](https://en.wikipedia.org/wiki/Literate_programming).  Your maintainers will thank you!

Life can be a bit sucky sometimes (most times?) so I thought it important to go ahead and include your change, such that we can all feel the brief feeling we make a difference in the world.

https://github.com/AE1020/AE1020.github.io/commit/32d297a50c6b8323a1d6d1f3e5eadc8014ec1228

Have a nice day.  :-)

https://www.youtube.com/watch?v=uCg2BoKiuOM

**Comment by rdiez** [comment]
> such that we can all feel the brief feeling we make a difference in the world

Yeah, we developers are the best, no doubt! ;-)
